apiVersion: apps/v1
kind: Deployment
metadata:
  name: nublado2
  labels:
    app: nublado2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nublado2
  template:
    metadata:
      labels:
        name: nublado2
    spec:
      containers:
        - name: app
          imagePullPolicy: "Always"
          # Use images field in a Kustomization to regularly set/update image tag
          image: "lsstsqre/nublado2"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: nublado2
