jupyterhub:
  debug:
    enabled: true

  hub:
    image:
      name: lsstsqre/nublado2
      tag: dev
      pullPolicy: Never

    extraConfig:
      nublado.py: |
        import nublado2.hub_config
        nublado2.hub_config.HubConfig().configure(c)

  auth:
    state:
      cryptoKey: "080c6d0eb8d9f84ef5f0860bea71dba6ab2e1be712c7bc8c2eaf92321c9fd968"

  proxy:
    secretToken: "3854245f5b48412ee9b7a2c985da6acdc146f80cc4f10eb175f0efa24530399b"
    service:
      type: ClusterIP

  ingress:
    hosts: ["minikube.lsst.codes"]
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://minikube.lsst.codes:31337/login"
      nginx.ingress.kubernetes.io/auth-url: "https://minikube.lsst.codes:31337/auth?scope=exec:notebook"

config:
  user_resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: "{user}"
