jupyterhub:
  debug:
    enabled: true

  hub:
    image:
      name: lsstsqre/nublado2
      tag: dev
      pullPolicy: Never

    extraConfig:
      nublado.py: |
        import nublado2.hub_config
        nublado2.hub_config.HubConfig().configure(c)

  singleuser:
    storage:
      type: none

  ingress:
    hosts: ["minikube.lsst.codes"]
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://minikube.lsst.codes:31337/login"
      nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr-service.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:notebook"

config:
  options_form:
    images_url: "http://cachemachine-dev.cachemachine-dev.svc.cluster.local/cachemachine/jupyter/available"
    images:
      - name: Weekly 42
        image_url: registry.hub.docker.com/lsstsqre/sciplat-lab:w_2020_42
    sizes:
      - name: Tiny
        cpu: .5
        ram: 1536M
      - name: Small
        cpu: 1
        ram: 3072M
      - name: Medium
        cpu: 2
        ram: 6144M
      - name: Large
        cpu: 4
        ram: 12288M
  user_resources: {}

vault_secret_path: "secret/k8s_operator/minikube.lsst.codes/nublado2"
