jupyterhub:
  debug:
    enabled: true

  hub:
    image:
      name: lsstsqre/nublado2
      tag: dev
      pullPolicy: Never

    extraConfig:
      nublado.py: |
        import nublado2.hub_config
        nublado2.hub_config.HubConfig().configure(c)

  singleuser:
    storage:
      type: none

  auth:
    state:
      cryptoKey: "080c6d0eb8d9f84ef5f0860bea71dba6ab2e1be712c7bc8c2eaf92321c9fd968"

  proxy:
    secretToken: "3854245f5b48412ee9b7a2c985da6acdc146f80cc4f10eb175f0efa24530399b"
    service:
      type: ClusterIP

  ingress:
    hosts: ["minikube.lsst.codes"]
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://minikube.lsst.codes:31337/login"
      nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr-service.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:notebook"

config:
  options_form:
    images:
      - name: Recommended
        image: registry.hub.docker.com/jupyterhub/k8s-singleuser-sample:0.9.0-n358.h11c2aeb8
      - name: Weekly 44
        image: registry.hub.docker.com/lsstsqre/sciplat-lab:w_2020_44
      - name: Weekly 43
        image: registry.hub.docker.com/lsstsqre/sciplat-lab:w_2020_43
      - name: Weekly 42
        image: registry.hub.docker.com/lsstsqre/sciplat-lab:w_2020_42
    sizes:
      - name: Tiny
        cpu: .5
        ram: 1536M
      - name: Small
        cpu: 1
        ram: 3072M
      - name: Medium
        cpu: 2
        ram: 6144M
      - name: Large
        cpu: 4
        ram: 12288M
  user_resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: "{user}"
